// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetList } from "./AssetList";

/**
 * ASSETMAP.xml - Core UUID to file path mapping
 */
export type AssetMap = { Id: string, AnnotationText: string | null, Creator: string | null, VolumeCount: number, IssueDate: string, Issuer: string | null, AssetList: AssetList, };
