// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentVersionList } from "./ContentVersionList";
import type { EssenceDescriptorList } from "./EssenceDescriptorList";
import type { LanguageString } from "./LanguageString";
import type { LocaleList } from "./LocaleList";
import type { SegmentList } from "./SegmentList";

/**
 * Root CPL structure - defines a complete IMF composition
 */
export type CompositionPlaylist = { id: string, annotation: LanguageString | null, issueDate: string, issuer: LanguageString | null, creator: LanguageString | null, contentOriginator: LanguageString | null, contentTitle: LanguageString, contentKind: string, contentVersionList: ContentVersionList | null, localeList: LocaleList | null, essenceDescriptorList: EssenceDescriptorList | null, segmentList: SegmentList, };
