// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageList } from "./LanguageList";
import type { RegionList } from "./RegionList";

export type Locale = { LanguageList: LanguageList | null, RegionList: RegionList | null, };
