// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceList } from "./ResourceList";

export type MainImageSequence = { Id: string, TrackId: string, ResourceList: ResourceList, };
