// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageString } from "./LanguageString";
import type { MarkerInfo } from "./MarkerInfo";

export type Resource = { Id: string, Annotation: LanguageString | null, EditRate: string | null, IntrinsicDuration: bigint, SourceDuration: bigint | null, SourceEncoding: string | null, TrackFileId: string | null, Marker: MarkerInfo | null, };
