// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MainAudioSequence } from "./MainAudioSequence";
import type { MainImageSequence } from "./MainImageSequence";
import type { MarkerSequence } from "./MarkerSequence";
import type { SubtitlesSequence } from "./SubtitlesSequence";

export type SequenceList = { MarkerSequence: Array<MarkerSequence> | null, mainImageSequences: Array<MainImageSequence> | null, mainAudioSequences: Array<MainAudioSequence> | null, subtitlesSequences: Array<SubtitlesSequence> | null, };
