// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VOLINDEX.xml - Entry point to IMF package
 */
export type VolumeIndex = { Index: number, };
