[package]
name = "imferno"
version = "0.1.0"
edition = "2021"
description = "Command-line interface for SMPTE ST 2067 IMF packages"
license = "MIT"
authors = ["JP Wesselink <jpwesselink@gmail.com>"]
repository = "https://github.com/jpwesselink/imferno"
readme = "../../README.md"

[[bin]]
name = "imferno"
path = "src/main.rs"

[dependencies]
imferno-core = { path = "../imferno-core", version = "0.1.0" }
clap = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
comfy-table = "7.1"
