// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChunkList } from "./ChunkList";

export type Asset = { Id: string, PackingList: boolean | null, ChunkList: ChunkList, };
