// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Track information with codec details
 */
export type TrackInfo = { trackId: string, trackType: string, codec: string, language: string | null, channels: string | null, formatDetails: string | null, resolution: string | null, framerate: string | null, bitDepth: string | null, subtitleType: string | null, };
