// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EssenceDescriptor } from "./EssenceDescriptor";

export type EssenceDescriptorList = { EssenceDescriptor: Array<EssenceDescriptor>, };
