// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * String with optional language attribute
 */
export type LanguageString = { text: string, language: string | null, };
