[package]
name = "imferno-core"
version = "0.1.0"
edition = "2021"
description = "SMPTE ST 2067 IMF parser and validator"
license = "MIT"
authors = ["Pathé Home Team"]
repository = "https://github.com/jpwesselink/imferno"

[features]
default = []
wasm       = ["dep:tsify", "dep:wasm-bindgen"]
typescript = ["dep:ts-rs"]
xmlsec1    = ["dep:tempfile"]

[dependencies]
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true }
quick-xml    = { workspace = true, features = ["serialize"] }
uuid         = { workspace = true, features = ["serde"] }
thiserror    = { workspace = true }
regex        = { workspace = true }
sha1         = { workspace = true }
sha2         = { workspace = true }
base64       = { workspace = true }
chrono       = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
ts-rs        = { version = "9.0",  optional = true }
tsify        = { version = "0.4",  optional = true }
tempfile     = { workspace = true, optional = true }
xmlsec       = { version = "0.3.0", optional = true }
libxml       = { version = "0.3.8", optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile          = { workspace = true }
