//! Typed validation-code catalogue for SMPTE ST 2067-202 (ISXD Plug-in).
//!
//! Edition note (AUDIT-2): the publication is **ST 2067-202:2023** (title
//! page of the publication PDF). The XML namespace year is frozen at
//! `/2022/` (§6 Table 1) — namespace year and edition year deliberately
//! differ, as with ST 2067-203/-204.

use crate::diagnostics::codes::ValidationCode;
use crate::diagnostics::{Category, Severity};

// ─────────────────────────────────────────────────────────────────────────────
// Spec-agnostic reason codes
// ─────────────────────────────────────────────────────────────────────────────

/// Spec-agnostic reason codes for ISXD Plug-in validation.
///
/// Passed to each edition's `for_code` dispatch function to get the full
/// `&'static str` code without any runtime string building.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IsxdCode {
    /// ISXDDataEssenceDescriptor: NamespaceURI is absent — Req item per §9.2 Table 5.
    NamespaceUriMissing,
    /// ISXDSequence shall contain at least one Resource (§6).
    ISXDSequenceNoResources,
    /// ISXDSequence Resource.SourceEncoding does not reference an ISXDDataEssenceDescriptor (§6).
    ISXDSequenceSourceEncodingInvalid,
    /// ISXD Track Files referenced by the same ISXD Virtual Track have inconsistent NamespaceURI values (§6).
    NamespaceUriMismatch,
    /// ISXD Virtual Track Edit Rate shall equal the Main Image Virtual Track Edit Rate (§6).
    EditRateMismatch,
}

// ─────────────────────────────────────────────────────────────────────────────
// Edition-specific enum (generated by macro)
// ─────────────────────────────────────────────────────────────────────────────

macro_rules! define_isxd_enum {
    ($name:ident, $prefix:literal) => {
        /// ISXD Plug-in validation codes, edition
        #[doc = $prefix]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, strum::EnumIter)]
        pub enum $name {
            /// ISXDDataEssenceDescriptor: NamespaceURI is absent — Req item per §9.2 Table 5.
            NamespaceUriMissing,
            /// ISXDSequence shall contain at least one Resource (§6).
            ISXDSequenceNoResources,
            /// ISXDSequence Resource.SourceEncoding does not reference an ISXDDataEssenceDescriptor (§6).
            ISXDSequenceSourceEncodingInvalid,
            /// ISXD Track Files referenced by the same ISXD Virtual Track have inconsistent NamespaceURI values (§6).
            NamespaceUriMismatch,
            /// ISXD Virtual Track Edit Rate shall equal the Main Image Virtual Track Edit Rate (§6).
            EditRateMismatch,
        }

        impl ValidationCode for $name {
            fn code(&self) -> &'static str {
                match self {
                    Self::NamespaceUriMissing               => concat!($prefix, ":9.2/NamespaceUriMissing"),
                    Self::ISXDSequenceNoResources           => concat!($prefix, ":6/ISXDSequenceNoResources"),
                    Self::ISXDSequenceSourceEncodingInvalid => concat!($prefix, ":6/ISXDSequenceSourceEncodingInvalid"),
                    Self::NamespaceUriMismatch              => concat!($prefix, ":6/NamespaceUriMismatch"),
                    Self::EditRateMismatch                  => concat!($prefix, ":6/EditRateMismatch"),
                }
            }
            fn description(&self) -> &'static str {
                match self {
                    Self::NamespaceUriMissing =>
                        "ISXDDataEssenceDescriptor: NamespaceURI shall be present (§9.2 Table 5, Req).",
                    Self::ISXDSequenceNoResources =>
                        "ISXDSequence shall contain at least one Resource.",
                    Self::ISXDSequenceSourceEncodingInvalid =>
                        "ISXDSequence Resource.SourceEncoding does not reference an ISXDDataEssenceDescriptor.",
                    Self::NamespaceUriMismatch =>
                        "All ISXD Track Files referenced by an ISXD Virtual Track shall have an identical NamespaceURI value (§6).",
                    Self::EditRateMismatch =>
                        "The Edit Rate of an ISXD Virtual Track shall be equal to the Edit Rate of the Main Image Virtual Track (§6).",
                }
            }
            fn default_severity(&self) -> Severity {
                // All of these are SHALL statements (§6, §9.2 Table 5 Req) —
                // Error across the board (AUDIT-20 fixed the previous
                // NamespaceUriMissing Warning).
                Severity::Error
            }
            fn category(&self) -> Category {
                // ISXD carries dynamic data essence (sidecar metadata
                // streams). Not audio — the previous tagging was wrong.
                Category::Data
            }
            fn example(&self) -> Option<&'static str> {
                Some(match self {
                    Self::NamespaceUriMissing =>
                        "<ISXDDataEssenceDescriptor>  <!-- missing required <NamespaceURI>… --> </ISXDDataEssenceDescriptor>",
                    Self::ISXDSequenceNoResources =>
                        "<ISXDSequence><ResourceList/></ISXDSequence>",
                    Self::ISXDSequenceSourceEncodingInvalid =>
                        "<ISXDSequence>…<SourceEncoding>urn:uuid:…</SourceEncoding></ISXDSequence>  <!-- UUID doesn't resolve to an ISXDDataEssenceDescriptor -->",
                    Self::NamespaceUriMismatch =>
                        "Two ISXDSequences with the same TrackId point at descriptors whose <NamespaceURI> differs.",
                    Self::EditRateMismatch =>
                        "ISXDSequence Resource with <EditRate>48 1</EditRate> in a Composition whose Main Image Virtual Track runs at 24000/1001.",
                })
            }
        }

        impl $name {
            pub const ALL: &'static [Self] = &[
                Self::NamespaceUriMissing,
                Self::ISXDSequenceNoResources,
                Self::ISXDSequenceSourceEncodingInvalid,
                Self::NamespaceUriMismatch,
                Self::EditRateMismatch,
            ];

            /// Dispatch from the spec-agnostic [`IsxdCode`] to this
            /// edition's static code string. Used by the shared validator helpers.
            pub fn for_code(r: IsxdCode) -> &'static str {
                match r {
                    IsxdCode::NamespaceUriMissing               => concat!($prefix, ":9.2/NamespaceUriMissing"),
                    IsxdCode::ISXDSequenceNoResources           => concat!($prefix, ":6/ISXDSequenceNoResources"),
                    IsxdCode::ISXDSequenceSourceEncodingInvalid => concat!($prefix, ":6/ISXDSequenceSourceEncodingInvalid"),
                    IsxdCode::NamespaceUriMismatch              => concat!($prefix, ":6/NamespaceUriMismatch"),
                    IsxdCode::EditRateMismatch                  => concat!($prefix, ":6/EditRateMismatch"),
                }
            }
        }

        impl From<$name> for String {
            fn from(c: $name) -> String {
                c.code().to_string()
            }
        }
    };
}

define_isxd_enum!(St2067_202_2023, "ST2067-202:2023");
