//! Typed validation-code catalogue for SMPTE ST 2067-203 (S-ADM Audio
//! Plug-in, 2023) and ST 2067-204 (ADM Audio Plug-in, 2023).
//!
//! The two specs are structural mirrors: identical CPL-level element
//! shape, distinct namespace URIs (`.../2067-203/2022` vs
//! `.../2067-204/2022`, both frozen at `/2022/` even in the 2023
//! publications — same edition-vs-namespace-year split as ST 2067-202,
//! see the AUDIT-2 note in `isxd_codes.rs`). One shared reason-code
//! enum drives two edition-specific `for_code` dispatch functions via a
//! macro, matching the pattern used by the IAB / ISXD plug-in
//! catalogues.

use crate::diagnostics::codes::ValidationCode;
use crate::diagnostics::{Category, Severity};

// ─────────────────────────────────────────────────────────────────────────────
// Spec-agnostic reason codes (shared between -203 and -204)
// ─────────────────────────────────────────────────────────────────────────────

/// Spec-agnostic reason codes for S-ADM / ADM Plug-in validation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SadmCode {
    /// A `*SignalSequence` / `*AudioSequence` is present in the CPL but no
    /// matching `*VirtualTrackParameterSet` (whose `TrackId` equals the
    /// sequence's `TrackId`) appears under `ExtensionProperties` — §5.4
    /// makes the parameter set mandatory when the corresponding sequence
    /// type is used.
    VirtualTrackParameterSetMissing,
    /// A `*VirtualTrackParameterSet` in `ExtensionProperties` names a
    /// `TrackId` that doesn't match any `*SignalSequence` /
    /// `*AudioSequence` in the same CPL — an orphaned parameter set with
    /// nothing to configure.
    VirtualTrackParameterSetOrphaned,
    /// A `*SignalSequence` / `*AudioSequence` has an empty `ResourceList`
    /// (no Resource children). Trivially non-playable per the shared
    /// SequenceType constraint in ST 2067-3 §7.2.
    SignalSequenceNoResources,
    /// A `*VirtualTrackParameterSet.MGASADMOperationalMode` (resp.
    /// `ADMOperationalMode`) is empty. §5.4 requires a URI naming the
    /// operational mode.
    OperationalModeEmpty,
    /// A `*SoundfieldGroupSelector.ResourceId` doesn't match any
    /// Resource `Id` in the corresponding SignalSequence's ResourceList —
    /// the selector points at a resource that isn't in the track. §5.4.
    SoundfieldGroupSelectorResourceIdOrphaned,
}

// ─────────────────────────────────────────────────────────────────────────────
// Edition-specific enums generated by macro
// ─────────────────────────────────────────────────────────────────────────────

macro_rules! define_sadm_enum {
    ($name:ident, $prefix:literal) => {
        /// S-ADM / ADM Plug-in validation codes, edition
        #[doc = $prefix]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, strum::EnumIter)]
        pub enum $name {
            VirtualTrackParameterSetMissing,
            VirtualTrackParameterSetOrphaned,
            SignalSequenceNoResources,
            OperationalModeEmpty,
            SoundfieldGroupSelectorResourceIdOrphaned,
        }

        impl ValidationCode for $name {
            fn code(&self) -> &'static str {
                match self {
                    Self::VirtualTrackParameterSetMissing =>
                        concat!($prefix, ":5.4/VirtualTrackParameterSetMissing"),
                    Self::VirtualTrackParameterSetOrphaned =>
                        concat!($prefix, ":5.4/VirtualTrackParameterSetOrphaned"),
                    Self::SignalSequenceNoResources =>
                        concat!($prefix, ":5.3/SignalSequenceNoResources"),
                    Self::OperationalModeEmpty =>
                        concat!($prefix, ":5.4/OperationalModeEmpty"),
                    Self::SoundfieldGroupSelectorResourceIdOrphaned =>
                        concat!($prefix, ":5.4/SoundfieldGroupSelectorResourceIdOrphaned"),
                }
            }
            fn description(&self) -> &'static str {
                match self {
                    Self::VirtualTrackParameterSetMissing =>
                        "A SignalSequence / AudioSequence has no matching VirtualTrackParameterSet (§5.4).",
                    Self::VirtualTrackParameterSetOrphaned =>
                        "A VirtualTrackParameterSet references a TrackId that no SignalSequence in the CPL uses (§5.4).",
                    Self::SignalSequenceNoResources =>
                        "A SignalSequence / AudioSequence has an empty ResourceList (ST 2067-3 §7.2).",
                    Self::OperationalModeEmpty =>
                        "A VirtualTrackParameterSet.OperationalMode is empty; §5.4 requires a URI.",
                    Self::SoundfieldGroupSelectorResourceIdOrphaned =>
                        "A SoundfieldGroupSelector.ResourceId names a Resource not present in the SignalSequence's ResourceList (§5.4).",
                }
            }
            fn default_severity(&self) -> Severity {
                // §5.4 items are SHALL statements — Error across the board.
                // ST 2067-3 §7.2 empty-ResourceList is also SHALL.
                Severity::Error
            }
            fn category(&self) -> Category {
                Category::Audio
            }
            fn example(&self) -> Option<&'static str> {
                Some(match self {
                    Self::VirtualTrackParameterSetMissing =>
                        "<SequenceList>…<MGASADMSignalSequence><TrackId>urn:uuid:aaa…</TrackId>…</MGASADMSignalSequence></SequenceList> with <ExtensionProperties/> (no matching MGASADMVirtualTrackParameterSet).",
                    Self::VirtualTrackParameterSetOrphaned =>
                        "<ExtensionProperties><MGASADMVirtualTrackParameterSet><TrackId>urn:uuid:bbb…</TrackId>…</MGASADMVirtualTrackParameterSet></ExtensionProperties> and no SignalSequence carries that TrackId.",
                    Self::SignalSequenceNoResources =>
                        "<MGASADMSignalSequence>…<ResourceList/></MGASADMSignalSequence>",
                    Self::OperationalModeEmpty =>
                        "<MGASADMVirtualTrackParameterSet>…<MGASADMOperationalMode></MGASADMOperationalMode>…</MGASADMVirtualTrackParameterSet>",
                    Self::SoundfieldGroupSelectorResourceIdOrphaned =>
                        "<MGASADMSoundfieldGroupSelector><ResourceId>urn:uuid:ccc…</ResourceId>…</MGASADMSoundfieldGroupSelector> where ccc… doesn't match any Resource.Id in the referenced SignalSequence.",
                })
            }
        }

        impl $name {
            pub const ALL: &'static [Self] = &[
                Self::VirtualTrackParameterSetMissing,
                Self::VirtualTrackParameterSetOrphaned,
                Self::SignalSequenceNoResources,
                Self::OperationalModeEmpty,
                Self::SoundfieldGroupSelectorResourceIdOrphaned,
            ];

            /// Dispatch from the spec-agnostic [`SadmCode`] to this edition's
            /// static code string. Used by the shared validator helpers.
            pub fn for_code(r: SadmCode) -> &'static str {
                match r {
                    SadmCode::VirtualTrackParameterSetMissing =>
                        concat!($prefix, ":5.4/VirtualTrackParameterSetMissing"),
                    SadmCode::VirtualTrackParameterSetOrphaned =>
                        concat!($prefix, ":5.4/VirtualTrackParameterSetOrphaned"),
                    SadmCode::SignalSequenceNoResources =>
                        concat!($prefix, ":5.3/SignalSequenceNoResources"),
                    SadmCode::OperationalModeEmpty =>
                        concat!($prefix, ":5.4/OperationalModeEmpty"),
                    SadmCode::SoundfieldGroupSelectorResourceIdOrphaned =>
                        concat!($prefix, ":5.4/SoundfieldGroupSelectorResourceIdOrphaned"),
                }
            }
        }

        impl From<$name> for String {
            fn from(c: $name) -> String {
                c.code().to_string()
            }
        }
    };
}

define_sadm_enum!(St2067_203_2023, "ST2067-203:2023");
define_sadm_enum!(St2067_204_2023, "ST2067-204:2023");
