// Auto-generated by `cargo xtask generate-codes-ts` — do not edit.
// ESM re-export of the CJS codes module.
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { codes } = require("./codes.js");
export { codes };
