/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getVersion(): string

export declare function parseAssetmap(xml: string): any

export declare function parseCpl(xml: string): any

export declare function parsePkl(xml: string): any

export declare function parseVolindex(xml: string): any

export declare function validate(files: Record<string, string>, options?: any | undefined | null): any

export declare function validatePath(path: string, options?: any | undefined | null): any
