/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Returns the imferno library version string.
 */
export declare function getVersion(): string

/**
 * Validate an IMF package from in-memory XML strings.
 *
 * @param files - A map of filename to XML content (e.g. `{ "ASSETMAP.xml": "..." }`)
 * @param options - Optional validation options (`coreSpec`, `app2eSpec`, `rules`, etc.)
 * @returns An `ImfReport` object with `package`, `cpls`, and `validation` fields.
 */
export declare function buildReport(files: Record<string, string>, options?: any | undefined | null): any

/**
 * Validate an IMF package directory on disk.
 *
 * @param path - Path to the IMP directory
 * @param options - Optional validation options (`coreSpec`, `app2eSpec`, `skipDiskChecks`, `rules`, etc.)
 * @returns An `ImfReport` object with `package`, `cpls`, and `validation` fields.
 */
export declare function buildReportFromPath(path: string, options?: any | undefined | null): any

/**
 * Pretty-print an `ImfReport` as a human-readable string.
 *
 * @param report - A previously returned `ImfReport` object
 * @returns A formatted plain-text report string.
 */
export declare function formatReport(report: any): string

/**
 * Parse an IMF package from in-memory XML strings, returning the full parsed package.
 *
 * Unlike `buildReport` which returns a validation summary, this returns the
 * complete `Imferno` struct with all essence descriptors, locales, content versions, etc.
 *
 * @param files - A map of filename to XML content (e.g. `{ "ASSETMAP.xml": "..." }`)
 * @returns The full parsed Imferno package object.
 */
export declare function parsePackage(files: Record<string, string>): any

/**
 * Parse an IMF package directory on disk, returning the full parsed package.
 *
 * Unlike `buildReportFromPath` which returns a validation summary, this returns the
 * complete `Imferno` struct with all essence descriptors, locales, content versions, etc.
 *
 * @param path - Path to the IMP directory
 * @returns The full parsed Imferno package object.
 */
export declare function parsePackageFromPath(path: string): any
